import Link from 'next/link'

export default function GameIndexPage() {
  const featuredGames = [
    {
      name: 'snake',
      slug: 'snake',
      description: 'A classic retro game that will challenge your reflexes.',
      icon: '🐍',
    },
    {
      name: 'Gomoku',
      slug: 'gomoku',
      description: 'Strategy game, the player who connects five in a row wins.',
      icon: '⚪',
    },
    {
      name: '2048',
      slug: '2048',
      description: 'Slide the tiles and try to create a tile with the number 2048.',
      icon: '🔢',
    },

    {
      name: 'Minesweeper',
      slug: 'minesweeper',
      description: 'Uncover all the safe squares without detonating any mines.',
      icon: '💣',
    },
    {
      name: 'Tetris',
      slug: 'tetris',
      description: 'A classic puzzle game where you stack falling blocks.',
      icon: '🧩',
    },
    {
      name: 'wordle',
      slug: 'wordle',
      description: 'A word guessing game where you have six attempts to guess a five-letter word.',
      icon: '🔤',
    },
    {
      name: 'Memory Match',
      slug: 'memory',
      description: 'A matching game where you need to find pairs of identical cards.',
      icon: '🧠',
    },
    {
      name: 'Othello',
      slug: 'othello',
      description: 'A strategy game where players take turns placing discs on a board.',
      icon: '⚫',
    },
    {
      name: 'Chinese Chess',
      slug: 'xiangqi',
      description: 'A traditional Chinese strategy game played on a grid.',
      icon: '🐎',
    },
  ]

  return (
    <div>
      <h1>Welcome to the Game Center</h1>
      <p style={{ color: '#ff0000' }}>All features are generated by https://v0.app/</p>

      <p style={{ color: '#666' }}>
        Please select a game from the left-hand menu, or enter directly from below:
      </p>

      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
          gap: '20px',
          marginTop: '20px',
        }}
      >
        {featuredGames.map((game) => (
          <Link
            href={`/game/${game.slug}`}
            key={game.slug}
            style={{ textDecoration: 'none', color: 'inherit' }}
          >
            <div
              style={{
                border: '1px solid #eaeaea',
                borderRadius: '12px',
                padding: '20px',
                textAlign: 'center',
                transition: 'transform 0.2s',
                cursor: 'pointer',
              }}
            >
              <span style={{ fontSize: '3rem' }}>{game.icon}</span>
              <h3>{game.name}</h3>
              <p style={{ fontSize: '0.9rem', color: '#888' }}>{game.description}</p>
            </div>
          </Link>
        ))}
      </div>
    </div>
  )
}
