import Link from 'next/link'
import { GAMES } from '@/lib/games'
import { useTranslations } from 'next-intl'

export default function GameIndexPage() {
  const t = useTranslations('gamelayout')
  return (
    <div>
      <h1>Welcome to the Game Center</h1>
      <p style={{ color: '#ff0000' }}>
        All features are generated by{' '}
        <a href="https://v0.app/" target="_blank" rel="noopener noreferrer">
          https://v0.app/
        </a>
      </p>

      <p style={{ color: '#666' }}>
        Please select a game from the left-hand menu, or enter directly from below:
      </p>

      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
          gap: '20px',
          marginTop: '20px',
        }}
      >
        {GAMES.map((game) => (
          <Link
            href={`/game/${game.slug}`}
            key={game.slug}
            style={{ textDecoration: 'none', color: 'inherit' }}
          >
            <div
              style={{
                border: '1px solid #eaeaea',
                borderRadius: '12px',
                padding: '20px',
                textAlign: 'center',
                transition: 'transform 0.2s',
                cursor: 'pointer',
              }}
            >
              <span style={{ fontSize: '3rem' }}>{game.icon}</span>
              <h3>{t(game.nameKey)}</h3>
              <p style={{ fontSize: '0.9rem', color: '#888' }}>{t(game.descriptionKey)}</p>
            </div>
          </Link>
        ))}
      </div>
    </div>
  )
}
